fix: check book-ci.yml
- 실제로 컨피그서버를 통해서 book-ci.yml 내부의 값을 잘 받아오는지 확인한다

#65

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -64,6 +64,10 @@ jobs:
             sleep 1
           done
 
+          echo "🔍 Fetching config from Config Server..."
+          curl --fail http://localhost:10332/book/ci | grep -E 'elasticsearch|redis|datasource' || echo "❌ Failed to fetch or grep config"
+
+
       - name: 🌐 Test connection to Elasticsearch
         run: |
           echo "Trying to connect to http://s4.java21.net:9200..."
